version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file: .env
    container_name: hs-discount-service-api
    network_mode: host
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    env_file: .env
    container_name: hs-discount-service-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    network_mode: host
