version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file: .env
    container_name: hs-discount-service-api
    ports:
      - ${PORT}:${PORT}
    networks:
      - hs-discount-service-network
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    env_file: .env
    container_name: hs-discount-service-postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - hs-discount-service-network

networks:
  hs-discount-service-network:
    driver: bridge
