FROM golang:1.15-alpine AS build

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /build

COPY . .
RUN go mod download
RUN go build -o app .

FROM scratch

COPY --from=build /build/app /

ENV APP_ENV=development

CMD [ "/app" ]
